# Nome do seu workflow do GitHub Actions
name: Generate Snake Animation

# Controles para quando o workflow será executado
on:
  # Executa automaticamente a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  
  # Permite que você execute este workflow manualmente na aba Actions
  workflow_dispatch:

# Uma única tarefa chamada "build" que fará todo o trabalho
jobs:
  build:
    # O tipo de máquina virtual para executar a tarefa
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Faz o checkout do seu repositório para que o workflow possa acessá-lo
      - uses: actions/checkout@v3

      # Passo 2: Gera a animação da cobra
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # O seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}

          # Lista de arquivos de saída
          # A animação será gerada e salva no arquivo output/snake.svg
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark
        env:
          # Token de acesso pessoal do GitHub, necessário para acessar suas contribuições
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Passo 3: Envia o arquivo gerado de volta para o seu repositório
      # Esta ação comita e envia as alterações automaticamente
      - name: Commit and Push Snake Animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update snake animation"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
